### ISSUE TITLE
Couldn't find file 'paper-button/paper-button'

### ISSUE THREAD

**Issue by piotrzaborow** [alchaplinsky/polymer-paper-rails#5]
I am a newbie in Polymer... but this seems more like rails problem. Did you have any idea why I can get it work?

I did it all. Installed gems, added to requires to application.js file.

**Comment by nahtnam** [comment]
Same here. Any way to fix this?

**Comment by nahtnam** [comment]
@piotrzaborow and @aravinthforever I figured it out.

Run:
```
rails g polymer:install
```

Then add this: `<%= html_import_tag 'application'%>` to your layout.

Finally, go to app/assets/components/application.html and add the components you want.

**Comment by olegsobchuk** [comment]
when you add some core or paper elements, you have to add it it application.html.erb

    #app/assets/components/application.html.erb

    //= require polymer/polymer
    //= require paper-button/paper-button

**Comment by sharden** [comment]
So did this work for anybody? Would be interested in seeing a sample project where this was implemented. I'm stuck at this require step.
